### ISSUE TITLE
Meal-web-app-setup

### ISSUE THREAD

**Issue by Christelle-12** [Christelle-12/Mealwebapp#21]
Hello,we are two in our group; @osmanwako and @Christelle-12 

- we created an empty repository with GitHub flow with the default branch developer
- we followed the steps described in curriculum-tools-copy-project
- we made the setup of our project with the Kanban board.
- Each of us assigned ourselves with the correct cards where Christelle is student A and Osman is student B
here is the link to the projects:https://github.com/Christelle-12/Mealwebapp/projects/1

**Comment by BregornOriginal** [comment]
Hi @Team 🔆  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a link to the Github project that you create.

- Kindly add a link to the project where you have the cards 


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by TadesseDev** [comment]
### Hi Team

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy (1)](https://user-images.githubusercontent.com/69077061/212969210-69f495ba-f2fb-4559-a222-d1507310d6fb.gif)


Cheers and Happy coding!👏👏👏
Please, remember to tag me in your question (if you have any) so I can receive the notification.
